# Python CircleCI 2.0 configuration file
version: 2
workflows:
    version: 2
    test:
        jobs:
        - test-3.8
        - test-3.6

jobs:
  test-3.8: &tests
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python tests/test_main.py

  test-3.6:
    <<: *tests
    docker:
      - image: circleci/python:3.6
